.TH "es.ull.esit.utils.Pair< F, S >" 3 "Sat Jan 28 2023" "Version v2" "ExpositoTOP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.ull.esit.utils.Pair< F, S >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPair\fP (F \fBfirst\fP, S \fBsecond\fP)"
.br
.ti -1c
.RI "boolean \fBequals\fP (Object o)"
.br
.ti -1c
.RI "int \fBhashCode\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static< A, B > \fBPair\fP< A, B > \fBcreate\fP (A a, B b)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "final F \fBfirst\fP"
.br
.ti -1c
.RI "final S \fBsecond\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBes\&.ull\&.esit\&.utils\&.Pair\fP< F, S >\&.\fBPair\fP (F first, S second)"

.SH "Member Function Documentation"
.PP 
.SS "static< A, B > \fBPair\fP< A, B > \fBes\&.ull\&.esit\&.utils\&.Pair\fP< F, S >\&.create (A a, B b)\fC [static]\fP"

.SS "boolean \fBes\&.ull\&.esit\&.utils\&.Pair\fP< F, S >\&.equals (Object o)"

.SS "int \fBes\&.ull\&.esit\&.utils\&.Pair\fP< F, S >\&.hashCode ()"

.SH "Member Data Documentation"
.PP 
.SS "final F \fBes\&.ull\&.esit\&.utils\&.Pair\fP< F, S >\&.first"

.SS "final S \fBes\&.ull\&.esit\&.utils\&.Pair\fP< F, S >\&.second"


.SH "Author"
.PP 
Generated automatically by Doxygen for ExpositoTOP from the source code\&.
