.TH "es.ull.esit.AppTest" 3 "Sat Jan 28 2023" "Version v2" "ExpositoTOP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.ull.esit.AppTest
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBshouldAnswerWithTrue\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Unit test for simple App\&. 
.SH "Member Function Documentation"
.PP 
.SS "void es\&.ull\&.esit\&.AppTest\&.shouldAnswerWithTrue ()"
Rigorous Test :-) 

.SH "Author"
.PP 
Generated automatically by Doxygen for ExpositoTOP from the source code\&.
