.TH "es.ull.esit.utilities.PowerSet< E >" 3 "Sat Jan 28 2023" "Version v2" "ExpositoTOP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.ull.esit.utilities.PowerSet< E > \- Sirve para calcular todos los subconjuntos de un conjunto dado\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Iterator< Set< E > >, and Iterable< Set< E > >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPowerSet\fP (Set< E > set)"
.br
.ti -1c
.RI "boolean \fBhasNext\fP ()"
.br
.ti -1c
.RI "Set< E > \fBnext\fP ()"
.br
.ti -1c
.RI "void \fBremove\fP ()"
.br
.ti -1c
.RI "Iterator< Set< E > > \fBiterator\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Sirve para calcular todos los subconjuntos de un conjunto dado\&. 


.PP
\fBParameters\fP
.RS 4
\fIstring\fP Hola A more detailed class description 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBes\&.ull\&.esit\&.utilities\&.PowerSet\fP< E >\&.\fBPowerSet\fP (Set< E > set)"

.SH "Member Function Documentation"
.PP 
.SS "boolean \fBes\&.ull\&.esit\&.utilities\&.PowerSet\fP< E >\&.hasNext ()"

.SS "Iterator< Set< E > > \fBes\&.ull\&.esit\&.utilities\&.PowerSet\fP< E >\&.iterator ()"

.SS "Set< E > \fBes\&.ull\&.esit\&.utilities\&.PowerSet\fP< E >\&.next ()"

.SS "void \fBes\&.ull\&.esit\&.utilities\&.PowerSet\fP< E >\&.remove ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for ExpositoTOP from the source code\&.
