.TH "es.ull.esit.utils" 3 "Sat Jan 28 2023" "Version v2" "ExpositoTOP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.ull.esit.utils
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPair\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ExpositoTOP from the source code\&.
