.TH "src/main/java/es/ull/esit/utilities/PowerSet.java" 3 "Sat Jan 28 2023" "Version v2" "ExpositoTOP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main/java/es/ull/esit/utilities/PowerSet.java
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBes\&.ull\&.esit\&.utilities\&.PowerSet< E >\fP"
.br
.RI "Sirve para calcular todos los subconjuntos de un conjunto dado\&. "
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBes\&.ull\&.esit\&.utilities\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ExpositoTOP from the source code\&.
