.TH "top.TOPTWRoute" 3 "Sat Jan 28 2023" "Version v2" "ExpositoTOP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
top.TOPTWRoute
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBgetPredeccesor\fP ()"
.br
.ti -1c
.RI "int \fBgetSuccesor\fP ()"
.br
.ti -1c
.RI "int \fBgetId\fP ()"
.br
.ti -1c
.RI "void \fBsetPredeccesor\fP (int pre)"
.br
.ti -1c
.RI "void \fBsetSuccesor\fP (int suc)"
.br
.ti -1c
.RI "void \fBsetId\fP (int id)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "int top\&.TOPTWRoute\&.getId ()"

.SS "int top\&.TOPTWRoute\&.getPredeccesor ()"

.SS "int top\&.TOPTWRoute\&.getSuccesor ()"

.SS "void top\&.TOPTWRoute\&.setId (int id)"

.SS "void top\&.TOPTWRoute\&.setPredeccesor (int pre)"

.SS "void top\&.TOPTWRoute\&.setSuccesor (int suc)"


.SH "Author"
.PP 
Generated automatically by Doxygen for ExpositoTOP from the source code\&.
