.TH "top.TOPTWEvaluator" 3 "Sat Jan 28 2023" "Version v2" "ExpositoTOP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
top.TOPTWEvaluator
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBevaluate\fP (\fBTOPTWSolution\fP solution)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static double \fBNO_EVALUATED\fP = \-1\&.0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void top\&.TOPTWEvaluator\&.evaluate (\fBTOPTWSolution\fP solution)"

.SH "Member Data Documentation"
.PP 
.SS "double top\&.TOPTWEvaluator\&.NO_EVALUATED = \-1\&.0\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ExpositoTOP from the source code\&.
