.TH "top.TOPTWReader" 3 "Sat Jan 28 2023" "Version v2" "ExpositoTOP" \" -*- nroff -*-
.ad l
.nh
.SH NAME
top.TOPTWReader
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBTOPTW\fP \fBreadProblem\fP (String filePath)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static \fBTOPTW\fP top\&.TOPTWReader\&.readProblem (String filePath)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ExpositoTOP from the source code\&.
